name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - name: Install is-odd globally and find its path
      run: |
        npm install -g is-odd
        which node
        npm root -g
        ls -la $(npm root -g)
        find $(npm root -g) -name is-odd -type d
    - run: npm test